{{ if .Values.Secrets.Create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-wifipass-portail
  labels:
    app.kubernetes.io/name: {{ .Values.AppName }}
    app.kubernetes.io/part-of: {{ .Values.AppPartOf }}
    app.kubernetes.io/component: {{ .Values.AppComponent }}
stringData:
  host: "mysql.mysql-staging"
  port: "3306"
  user: "wifipass_portail"
  password: "password"
{{ end }}
