{{ if .Values.Ingress.EnablePhpFpm }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.AppName }}
    app.kubernetes.io/part-of: {{ .Values.AppPartOf }}
    app.kubernetes.io/component: {{ .Values.AppComponent }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: fastcgi
  selector:
    pod: {{ .Release.Name }}
{{ end }}
